version: '3.8'

services:
  php-apache:
    image: php:8.2-apache
    container_name: php-apache
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: #H!town$rdcRYAN410
      MYSQL_DATABASE: accounts
      MYSQL_USER: admin
      MYSQL_PASSWORD: #H!town$rdcRYAN410
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  
      

